services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/app
      # Fallback values if .env file is missing
      - AUTH0_DOMAIN=${AUTH0_DOMAIN:-dev-tenant.auth0.com}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE:-https://dev-fhir-api}
      - AUTH0_ALGORITHM=${AUTH0_ALGORITHM:-RS256}
      - JWKS_CACHE_TTL=${JWKS_CACHE_TTL:-3600}
      - AUTH_DEBUG=${AUTH_DEBUG:-true}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
    volumes:
      - ./backend:/app
      - /app/__pycache__
    networks:
      - ai-fhir-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      # Fallback values if .env.local file is missing
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-dev-secret-key-change-in-production}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID:-dev-client-id}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET:-dev-client-secret}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN:-dev-tenant.auth0.com}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE:-https://dev-fhir-api}
      - NEXTAUTH_DEBUG=${NEXTAUTH_DEBUG:-false}
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - ai-fhir-network
    depends_on:
      backend:
        condition: service_healthy

networks:
  ai-fhir-network:
    driver: bridge

volumes:
  node_modules:
  next_cache: